#ifndef HEAD_H
#define HEAD_H


#include <QObject>
#include <QWidget>
#include <QLabel>
#include <QTime>
#include <QPalette>
#include <QEvent>
#include <QPainter>
#include <QMenu>
#include <QMenuBar>
#include <QAction>
#include <QActionEvent>
#include <QPushButton>
#include <QTimer>
#include <QTimerEvent>
#include <QMenuBar>
#include <QToolButton>
#include <QFont>
#include <QPalette>
#include <QStyle>
#include <QPainter>
#include <QDialog>
#include <QEvent>
#include <QKeyEvent>
#include <QLineEdit>
#include <QStatusBar>
#include <QStatusTipEvent>
#include <QMessageBox>
#include <QString>
#include <QMouseEvent>
#include <QKeyEvent>
#include <QPen>
#include <QBrush>
#include <QPicture>
#include <QBitmap>
#include <QFile>
#include <QFileDevice>
#include <QFileInfo>
#include <QByteArray>
#include <QFileInfoList>
#include <QDateTime>
#include <QPoint>
#include <QPointer>
#include <QtEvents>
#include <QStringList>
#include <QLayout>
#include <QTimerEvent>
#include <QTimeEdit>
#include <QTimeLine>
#include <QToolBar>
#include <QToolButton>
#include <QStatusBar>
#include <QStatusTipEvent>
#include <QTextEdit>
#include <QDockWidget>
#include <iostream>
#include <QDebug>
#include <cmath>
#include <QKeyEventTransition>
#include <QCursor>
#include <QGraphicsItem>
#include <QGraphicsSceneMouseEvent>
#include <QDrag>
#include <QMimeData>
#include <QRectF>
#include <QGraphicsScene>
#include <QGraphicsView>
#include <QGraphicsRectItem>
#include <QGraphicsScene>
#include <QGraphicsView>
#include <QStyleOptionGraphicsItem>
#include <QGraphicsSceneDragDropEvent>
#include <QMap>
#include <QGraphicsTextItem>

#endif // HEAD_H
